stages:
  data_ingestion:
    cmd: python src/bbc_news/pipeline/stage_01_data_ingestion.py
    deps:
      - src/bbc_news/pipeline/stage_01_data_ingestion.py
      - config/config.yaml
    outs:
      - artifacts/data_ingestion/BBC-NEWS/BBC News Train.csv
      - artifacts/data_ingestion/BBC-NEWS/BBC News Test.csv
      - artifacts/data_ingestion/BBC-NEWS/BBC News Sample Solution.csv

  
  prepare_base_model:
    cmd: python src/bbc_news/pipeline/stage_02_prepare_base_model.py
    deps:
      - src/bbc_news/pipeline/stage_02_prepare_base_model.py
      - config/config.yaml
      - params.yaml
    outs:
      - artifacts/prepare_base_model/lstm_model.keras

  data_transformation:
    cmd: python src/bbc_news/pipeline/stage_03_data_transformation.py
    deps:
      - src/bbc_news/pipeline/stage_03_data_transformation.py
      - config/config.yaml
      - artifacts/data_ingestion/BBC-NEWS
    outs: 
      - artifacts/data_transformation/train.csv
      - artifacts/data_transformation/test.csv
      - artifacts/data_transformation/tokeniazer.joblib

  model_trainer:
    cmd: python src/bbc_news/pipeline/stage_04_model_trainer.py
    deps:
      - src/bbc_news/pipeline/stage_04_model_trainer.py
      - config/config.yaml
      - params.yaml
      - artifacts/data_transformation/train.csv
      - artifacts/data_transformation/test.csv 
      - artifacts/data_transformation/tokeniazer.joblib
    outs:
      - artifacts/model_trainer/model.keras
  
  model_evaluation:
    cmd: python src/bbc_news/pipeline/stage_05_model_evaluation_mlflow.py
    deps:
      - src/bbc_news/pipeline/stage_05_model_evaluation_mlflow.py
      - config/config.yaml
      - artifacts/model_trainer/model.keras
      - artifacts/data_transformation/tokeniazer.joblib
    outs:
      - artifacts/model_evaluation/metrics.json