---
features:
  MAX_FEATURES: 10000
  MAX_TEXT_LENGTH: 200
  NUM_CATEGORY: 1
lstm:
  LOSS: categorical_crossentropy
  OPTIMIZER: adam
  ACTIVATION: softmax
  DROPOUT: 0.2
  EMBEDDING_DIM: 128
  METRICS: accuracy
  LEARNING_RATE: 0.01
  BATCH_SIZE: 16
  EPOCHS: 1
  UNITS: 64