artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://github.com/SunilKumar-ugra/Datasets/raw/master/BBC-NEWS.zip
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion

prepare_base_model:
  root_dir: artifacts/prepare_base_model
  base_model_path: artifacts/prepare_base_model/base_model.h5
  updated_base_model_path: artifacts/prepare_base_model/base_model_updated.h5
  lstm_model_path: artifacts/prepare_base_model/lstm_model.keras

data_transformation:
  root_dir: artifacts/data_transformation
  train_data_path: artifacts/data_ingestion/BBC-NEWS/BBC News Train.csv
  test_data_path: artifacts/data_ingestion/BBC-NEWS/BBC News Test.csv
  tokeniazer_path: artifacts/data_transformation/tokeniazer.joblib

model_trainer:
  root_dir: artifacts/model_trainer
  trained_model_path: artifacts/model_trainer/model.keras
  train_data_path: artifacts/data_transformation/train.csv
  test_data_path: artifacts/data_transformation/test.csv
